{
    "openapi":"3.0.0",
    "info":{
        "title": "user documentation",
        "description": "this is user documentation",
        "version": "1.0.0",
        "contact": {
            "email":"souza.marcosv2@gmail.com"
            
        }
    },
    "paths":{
        "/users":{
            "post":{
                "tags" :["users"],
                "summary":"Criar um novo usuario",
                "description": "Create a new user",
                "requestBody":{
                    "content":{
                        "application/json":{
                        "schema": {
                            "$ref": "#/components/schemas/User"
                        },
                        "examples":{
                            "user":{
                                "value":{
                                    "name": "Marcos Vinicius",
                                   "email": "marcos@gmail.com.br"

                                }
                            }
                                    
                        }
                      }
                    }
                },
                "responses":{
                    "201": {
                        "description": "operação realizada com sucesso",
                          "content":{
                            "application/json":{
                              "schema": {
                                  "type": "object",
                               "$ref":"#/components/schemas/User"
                                 
                                
                            }
                            }
                        }
                    },
                    "400":{
                        "description":"Email ja está sendo ultilizado.",
                        "content":{
                            "application/json":{ 
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "error": "this email is already in use."                                    }
                                }
                            }
                         }
                        
                        }
                    
                    
                }
            },
            "get": {
                "tags" :["users"],
                "summary": "Retorna todos os usuarios",
                "description": "List of all users, only allowed for admins",
                "parameters": [
                  {
                    "name": "user_id",
                    "in": "header",
              
                    "required": true,
                    "type": "string"
                   
                  }
                ],
                "responses": {
                  "200": {
                    "description": "Operação realizada com sucesso.",
                    "content": {
                      "application/json": {
                        "schema": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "string"
                              },
                              "name": {
                                "type": "string"
                              },
                              "admin": {
                                "type": "boolean"
                              },
                              "email": {
                                "type": "string"
                              },
                              "created_at": {
                                "type": "date"
                              },
                              "updated_at": {
                                "type": "date"
                              }
                            }
                          },
                          "example": [
                            {
                              "admin": false,
                              "id": "34db44d2-34c7-49c0-bd81-535fc98e2236",
                              "name": "Marcos vinicius",
                              "email": "marcos.souza@example.com",
                              "created_at": "2021-11-19T19:40:09.455Z",
                              "updated_at": "2021-11-19T19:40:32.760Z"
                            },
                            {
                              "admin": true,
                              "id": "653046dc-3e53-413e-ae49-2a0508c988ff",
                              "name": "Maria de souza",
                              "email": "maria.souza@example.com",
                              "created_at": "2021-11-19T19:33:36.469Z",
                              "updated_at": "2021-11-19T19:33:36.469Z"
                            }
                          ]
                        }
                      }
                    }
                  },
                   "400":{
                       "description": "Usuario sem permissão ou Usuario não encontrado.",
                       "content":{
                        "application/json":{ 
                            "schema": {
                                "type": "object",
                                "example": {
                                    "error": "you need to be an administrator to list all users."                                    }
                            }
                        }
                     }
                   }
                   
               }
                
            }

                },
                "/users/{user_id}":{
                    "get": {
                        "tags" :["users"],
                        "summary": "Retorna um usuario especifico",
                        "parameters": [
                          {
                            "name": "user_id",
                            "in": "path",
                            "description":"ID do usuario",
                            "required": true,
                            "type": "string"
                          }
                        
                         
                        ],
                        "responses": {
                          "200": {
                            "description": "Operação realizada com sucesso.",
                            "content": {
                              "application/json": {
                                "schema": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "id": {
                                        "type": "string"
                                      },
                                      "name": {
                                        "type": "string"
                                      },
                                      "admin": {
                                        "type": "boolean"
                                      },
                                      "email": {
                                        "type": "string"
                                      },
                                      "created_at": {
                                        "type": "date"
                                      },
                                      "updated_at": {
                                        "type": "date"
                                      }
                                    }
                                  },
                                  "example": 
                                    {
                                      "admin": false,
                                      "id": "34db44d2-34c7-49c0-bd81-535fc98e2236",
                                      "name": "Marcos vinicius",
                                      "email": "marcos.souza@example.com",
                                      "created_at": "2021-11-19T19:40:09.455Z",
                                      "updated_at": "2021-11-19T19:40:32.760Z"
                                    }
                                
                                  
                                }
                              }
                            }
                          },
                           "400":{
                               "description": "Usuario sem permissão ou Usuario não encontrado.",
                               "content":{
                                "application/json":{ 
                                    "schema": {
                                        "type": "object",
                                        "example": {
                                            "error": "user not found."                                    }
                                    }
                                }
                             }
                           }
                           
                       }
                        
                    }
                },
                "/users/{user_id}/admin":{
                    "patch": {
                        "tags" :["users"],
                        "summary": "Torna admin um usuario",
                        "parameters": [
                          {
                            "name": "user_id",
                            "in": "path",
                            "description":"ID do usuario",
                            "required": true,
                            "type": "string"
                          }
                        
                         
                        ],
                        "responses": {
                          "200": {
                            "description": "Operação realizada com sucesso.",
                            "content": {
                              "application/json": {
                                "schema": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "id": {
                                        "type": "string"
                                      },
                                      "name": {
                                        "type": "string"
                                      },
                                      "admin": {
                                        "type": "boolean"
                                      },
                                      "email": {
                                        "type": "string"
                                      },
                                      "created_at": {
                                        "type": "date"
                                      },
                                      "updated_at": {
                                        "type": "date"
                                      }
                                    }
                                  },
                                  "example": 
                                  {
                                    "admin": true,
                                    "id": "653046dc-3e53-413e-ae49-2a0508c988ff",
                                    "name": "Maria de souza",
                                    "email": "maria.souza@example.com",
                                    "created_at": "2021-11-19T19:33:36.469Z",
                                    "updated_at": "2021-11-19T19:33:36.469Z"
                                  }
                                
                                  
                                }
                              }
                            }
                          },
                           "400":{
                               "description": "Usuario sem permissão ou Usuario não encontrado.",
                               "content":{
                                "application/json":{ 
                                    "schema": {
                                        "type": "object",
                                        "example": {
                                            "error": "user not found."                                    }
                                    }
                                }
                             }
                           }
                           
                       }
                        
                    }
                }
               
            
        
         
        
    },
   

     
    
    

    "components":{
        "schemas":{
            "User":{
                "type": "object",
                "properties":{
                    "admin":{
                        "type":"boolean"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "created_at": {
                       "type": "string"
                    },
                    "updated_at":  {
                        "type":"string"
                        
                    }
                }
            }
        }
    }
  
}